### ISSUE TITLE
Allow shacl validator to be pip installed

### ISSUE THREAD

**Issue by danieldaviestelicent** [Telicent-io/shacl-tool#1]
The shacl validator will be more useful if people are able to install it via pip. It should therefore be possible to build a wheel that we can deploy to our private repository in the future.

`owl2Shacl.py` will need to be put on the PATH. We have an example of doing that here: https://github.com/Telicent-io/telicent-deployments/blob/162-cli-config-file/cli/setup.cfg

**Comment by afizzycola** [comment]
@gnikolov95 @danieldaviestelicent Any update on getting this pip installable? I would like to add it to out mapper test template.

**Comment by gnikolov95** [comment]
@afizzycola It needs to be published to CodeArtifactory - git workflow needs to be added, will jump back on this once I finish with the ABAC reduction stuff.

https://github.com/Telicent-io/shacl-tool/pull/2 - This PR added the option do install it locally, if this is of any help.

**Comment by gnikolov95** [comment]
https://github.com/Telicent-io/shacl-tool/pull/3 Closes this issue.
